name: Publish nuget package

on: workflow_dispatch

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Working directory
      run: pwd
    - name: Working directory
      run: ls Publicizer/bin/Release/
    - name: The end
      run: echo "This is the end"
