name: Publish nuget package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/workflows/build-and-test.yml@main
    - name: The end
      run: echo "This is the end"
